### PR TITLE
React Calculator -  Milestone 1 finished

### PR DESCRIPTION
**Pull request by Flakster**
# This pull request includes

* Basic project structure: Github repo, ESlint, and Stylelint workflows, README.md
* React initialization with create-react-app
* Install of prop-types using npm for type checking props
* Install of  big.js using npm.
* Heroku deployment

### CODE REVIEW

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason:
- Kindly fix the linting issues before re-submitting.

**Comment by Flakster** [comment]
# Update

The issues reported by the linters were fixed

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @Flakster :hand: 
Awesome job on this milestone so far :+1: 
But we need to make some changes before moving on

- [x] We need to update the README file by adding descriptive information about the project. Right now the README lacks relevant information about the project since it still has the placeholder text generated by `create-react-app`.
Screenshot from 2021-02-03 13-37-02

- [x] Awesome work setting up the linter in your repo using Github actions. But we also need to add the eslint and stylint config file to your repository. Check the instructions [here](https://github.com/microverseinc/linters-config/tree/master/react-redux) at Set-up linters in your local env

Happy coding :computer: 
**Sergio Torres**

**Comment by Flakster** [comment]
# New Update
* Added a descriptive README.md file

**Comment by Flakster** [comment]
# New Update
* Added the ESlint and Stylelint config files to the repository

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

### Optional:

- [ ] Remove unnecessary and unused files in `public/` directory

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> gmail</a> &nbsp; &nbsp; [Twitter Follow](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [GitHub followers](https://github.com/PhillipUg)

**Pull request merged**
